server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native # Use native profile for local filesystem backend
  cloud:
    config:
      server:
        git:
          uri: git@github.com:MartinMSalas/config-server-personal-admin.git
          clone-on-start: true
          default-label: master
          native:
            search-locations: file:../config-repo/ # Points to a directory relative to where config-server runs
            # For a real Git repo, you would use:
            # git:
            #   uri: https://github.com/your-username/your-config-repo.git
            #   clone-on-start: true
            #   default-label: main
